apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: max-weather
resources:
  - ../base
images:
  - name: max-weather-app
    newName: 638599595074.dkr.ecr.ap-southeast-1.amazonaws.com/mw-prd-apse1-ecr-01
    newTag: "20260628171434"
